package Game;

/**
 *
 * @author glabka
 */
public enum MovesEnum {
    STANDARD, WHITE_KINGSIDE_CASTLING, WHITE_QUEENSIDE_CASTLING,
    BLACK_KINGSIDE_CASTLING, BLACK_QUEENSIDE_CASTLING, EN_PASSANT, PAWN_PROMOTION
}
